### ISSUE TITLE
aaaaaaaaaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by cybergrunge-ops** [MeltyPlayer/OoT3D-Importer#1]
stupid question but this does not support loading materials/textures yet does it

**Comment by MeltyPlayer** [comment]
This is based on https://github.com/M-1-RLG/io_scene_cmb, I just didn't fork it correctly. 😅

That plugin already supported textures/materials, but alpha materials and animated textures (e.g. eyes) are still WIP.

**Comment by cybergrunge-ops** [comment]
ohh haha. i been so like braindead after searchin thru all these random forums trawlin thru links and stuff lol i didnt even think to just search for the original
