### ISSUE TITLE
I can't import models and animations

### ISSUE THREAD

**Issue by Andree12** [MeltyPlayer/OoT3D-Importer#2]
![8129081237](https://user-images.githubusercontent.com/49048262/129142829-ffc0a7bb-f110-424c-8cd9-2dafc3aff47d.png)
I got this error when I use the latest version of the OoT3D-Importer plugin.
The version of Blender I used is 2.79b.

All the OoT3D-Importer versions before https://github.com/MeltyPlayer/OoT3D-Importer/tree/a04f70c2e8d3f51c4e4be9959abad8ae28af253c is were they all work with my Blender program.

Am I using the wrong version of Python or it is something else?

**Comment by MeltyPlayer** [comment]
Oops, that's embarassing. It's a typo from copying JS code into Python, I'm not sure how that didn't result in any errors on my end. I just pushed out a fix, let me know if it works for you.

**Comment by Andree12** [comment]
Oh thank you, it works.
